'use strict';

const crypto = require('crypto');
const fs = require('fs');
const path = require('path');
const express = require('express');
const helmet = require('helmet');
const rateLimit = require('express-rate-limit');
const { DatabaseSync } = require('node:sqlite');

const PORT = Number(process.env.PORT) || 3000;
const DB_PATH = process.env.DB_PATH || path.join(__dirname, 'data', 'cowhand.sqlite');
const USER = process.env.COWHAND_USER;
const PASS = process.env.COWHAND_PASS;
const PUBLIC_DIR = path.join(__dirname, 'public');

if (!USER || !PASS) {
  console.error('COWHAND_USER e COWHAND_PASS precisam estar definidos (veja .env.example). Encerrando.');
  process.exit(1);
}

fs.mkdirSync(path.dirname(DB_PATH), { recursive: true });
const db = new DatabaseSync(DB_PATH);
db.exec('PRAGMA journal_mode = WAL');
db.exec(`
  CREATE TABLE IF NOT EXISTS state (
    id INTEGER PRIMARY KEY CHECK (id = 1),
    data TEXT NOT NULL,
    version INTEGER NOT NULL,
    updated_at TEXT NOT NULL
  );
`);

function seedIfEmpty() {
  const row = db.prepare('SELECT id FROM state WHERE id = 1').get();
  if (row) return;
  const seedPath = path.join(__dirname, 'seed_data.json');
  const seed = JSON.parse(fs.readFileSync(seedPath, 'utf8'));
  db.prepare('INSERT INTO state (id, data, version, updated_at) VALUES (1, ?, 1, ?)')
    .run(JSON.stringify(seed), new Date().toISOString());
  console.log('Estado inicial semeado a partir de seed_data.json.');
}
seedIfEmpty();

/* ---------- auth ---------- */
// Hash both sides to a fixed-length digest before comparing, so differing input
// lengths don't take a measurably different code path (closes a minor timing side-channel).
function timingSafeCredentialEqual(provided, expected) {
  const a = crypto.createHash('sha256').update(String(provided)).digest();
  const b = crypto.createHash('sha256').update(String(expected)).digest();
  return crypto.timingSafeEqual(a, b);
}

function requireAuth(req, res, next) {
  const header = req.headers.authorization || '';
  const [scheme, encoded] = header.split(' ');
  if (scheme === 'Basic' && encoded) {
    let decoded = '';
    try { decoded = Buffer.from(encoded, 'base64').toString('utf8'); } catch (e) { decoded = ''; }
    const sep = decoded.indexOf(':');
    const user = sep === -1 ? decoded : decoded.slice(0, sep);
    const pass = sep === -1 ? '' : decoded.slice(sep + 1);
    if (timingSafeCredentialEqual(user, USER) && timingSafeCredentialEqual(pass, PASS)) {
      return next();
    }
  }
  res.set('WWW-Authenticate', 'Basic realm="cowhand"');
  res.status(401).send('Autenticação necessária.');
}

const authLimiter = rateLimit({
  windowMs: 60 * 1000,
  limit: 10,
  standardHeaders: true,
  legacyHeaders: false,
  message: 'Muitas tentativas. Tente novamente em instantes.',
  // only count requests that actually failed auth, so the two legitimate users
  // don't get locked out by normal polling once logged in
  skipSuccessfulRequests: true,
});

// Requests that mutate shared state are only ever made by our own page's JS (fetch with
// a relative URL), so a same-origin check here blocks CSRF: HTTP Basic credentials are
// resent by the browser to same-origin requests regardless of which page triggered them,
// so without this a malicious third-party page could still forge a PUT.
function requireSameOrigin(req, res, next) {
  const origin = req.headers.origin;
  if (origin) {
    let originHost;
    try { originHost = new URL(origin).host; } catch (e) { originHost = null; }
    if (originHost !== req.headers.host) {
      return res.status(403).json({ error: 'cross_origin_forbidden' });
    }
  }
  next();
}

/* ---------- input validation ----------
 * Enums are loaded from taxonomy.json (generated by build_app.py from the same
 * CATEGORIAS/SUBCATEGORIAS/... constants baked into the client) so the server never
 * drifts out of sync with what the UI actually offers. */
const taxonomy = JSON.parse(fs.readFileSync(path.join(__dirname, 'taxonomy.json'), 'utf8'));
const CATEGORIAS = new Set(taxonomy.CATEGORIAS);
const SUBCATEGORIAS = new Set(taxonomy.SUBCATEGORIAS);
const RESPONSAVEL_OPTS = new Set(taxonomy.RESPONSAVEL_OPTS);
const TIPO_OPTS = new Set(taxonomy.TIPO_OPTS);
const FORMA_PGTO_OPTS = new Set(taxonomy.FORMA_PGTO_OPTS);
const STATUS_OPTS = new Set(taxonomy.STATUS_OPTS);

function isPlainString(v, maxLen) {
  return typeof v === 'string' && v.length <= maxLen;
}
function isFiniteNumber(v) {
  return typeof v === 'number' && Number.isFinite(v);
}
function validTransacao(t) {
  return t && typeof t === 'object' &&
    isPlainString(t.id, 100) &&
    isPlainString(t.data, 20) &&
    isPlainString(t.descricao, 500) &&
    CATEGORIAS.has(t.categoria) &&
    (t.subcategoria === '' || SUBCATEGORIAS.has(t.subcategoria)) &&
    (t.formaPagamento === '' || FORMA_PGTO_OPTS.has(t.formaPagamento)) &&
    RESPONSAVEL_OPTS.has(t.responsavel) &&
    TIPO_OPTS.has(t.tipo) &&
    (t.status === undefined || STATUS_OPTS.has(t.status)) &&
    isPlainString(t.parcela || '', 20) &&
    isFiniteNumber(t.valor);
}
function validRecorrente(r) {
  return r && typeof r === 'object' &&
    isPlainString(r.id, 100) &&
    CATEGORIAS.has(r.categoria) &&
    (r.subcategoria === '' || SUBCATEGORIAS.has(r.subcategoria)) &&
    isPlainString(r.item, 200) &&
    RESPONSAVEL_OPTS.has(r.responsavel) &&
    (r.forma === '' || FORMA_PGTO_OPTS.has(r.forma)) &&
    TIPO_OPTS.has(r.tipo) &&
    isFiniteNumber(r.valorEsperado) &&
    isPlainString(r.parcela || '', 20) &&
    isPlainString(r.obs || '', 500) &&
    isPlainString(r.chave || '', 100);
}
function validMeta(m) {
  return m && typeof m === 'object' &&
    isPlainString(m.id, 100) &&
    isPlainString(m.nome, 200) &&
    isPlainString(m.subcategoria || '', 100) &&
    isFiniteNumber(m.valorAtual) &&
    isFiniteNumber(m.valorAlvo) &&
    isPlainString(m.prazo || '', 20) &&
    isFiniteNumber(m.contribPlanejada);
}
function validState(state) {
  if (!state || typeof state !== 'object') return false;
  if (typeof state.renda !== 'object' || !isFiniteNumber(state.renda.henrique) || !isFiniteNumber(state.renda.carol)) return false;
  if (!Array.isArray(state.transacoes) || state.transacoes.length > 20000 || !state.transacoes.every(validTransacao)) return false;
  if (!Array.isArray(state.recorrentes) || state.recorrentes.length > 500 || !state.recorrentes.every(validRecorrente)) return false;
  if (!Array.isArray(state.metas) || state.metas.length > 100 || !state.metas.every(validMeta)) return false;
  return true;
}

// index.html's app logic is a single inline <script> (no build step, no bundler) — rather
// than weakening CSP with 'unsafe-inline', allow exactly that script via a content hash
// computed from the file itself, so any *injected* inline script (e.g. via XSS) still
// won't match the hash and will be blocked by the browser.
function inlineScriptHash() {
  const html = fs.readFileSync(path.join(PUBLIC_DIR, 'index.html'), 'utf8');
  const match = html.match(/<script>([\s\S]*?)<\/script>/);
  if (!match) throw new Error('index.html: inline <script> not found, cannot compute CSP hash');
  // the HTML parser normalizes CRLF/CR to LF before exposing script text content, so the
  // hash must be computed over the same normalized text the browser actually hashes.
  const normalized = match[1].replace(/\r\n/g, '\n').replace(/\r/g, '\n');
  const digest = crypto.createHash('sha256').update(normalized, 'utf8').digest('base64');
  return `'sha256-${digest}'`;
}

const app = express();
app.disable('x-powered-by');
app.set('trust proxy', 1); // behind Coolify's reverse proxy; needed for correct rate-limit keying
app.use(helmet({
  contentSecurityPolicy: {
    directives: {
      defaultSrc: ["'self'"],
      // the app renders many elements with inline style="..." attributes (no CSS-in-JS
      // build step) — CSP has no hash/nonce mechanism for style *attributes* (only for
      // <style> blocks), so this directive can't be tightened further without rewriting
      // the renderer to use CSS classes instead. scriptSrc below stays strict: that's
      // where real code-execution risk lives, and it's still hash-locked.
      styleSrc: ["'self'", "'unsafe-inline'", "https://fonts.googleapis.com"],
      fontSrc: ["'self'", "https://fonts.gstatic.com"],
      scriptSrc: ["'self'", inlineScriptHash()],
      imgSrc: ["'self'", "data:"],
      connectSrc: ["'self'"],
      objectSrc: ["'none'"],
      baseUri: ["'none'"],
      frameAncestors: ["'none'"],
    },
  },
}));
app.use('/api', authLimiter);
app.use(requireAuth);
app.use(express.json({ limit: '2mb' }));

app.get('/api/state', (req, res) => {
  const row = db.prepare('SELECT data, version FROM state WHERE id = 1').get();
  res.json({ state: JSON.parse(row.data), version: row.version });
});

app.put('/api/state', requireSameOrigin, (req, res) => {
  const { state, version } = req.body || {};
  if (typeof version !== 'number' || !validState(state)) {
    return res.status(400).json({ error: 'invalid_payload' });
  }
  const current = db.prepare('SELECT data, version FROM state WHERE id = 1').get();
  if (current.version !== version) {
    return res.status(409).json({ state: JSON.parse(current.data), version: current.version });
  }
  const nextVersion = current.version + 1;
  const updatedAt = new Date().toISOString();
  state.updatedAt = updatedAt;
  db.prepare('UPDATE state SET data = ?, version = ?, updated_at = ? WHERE id = 1')
    .run(JSON.stringify(state), nextVersion, updatedAt);
  res.json({ version: nextVersion, updatedAt });
});

app.use(express.static(PUBLIC_DIR, { index: 'index.html' }));

// Centralized error handler: never leak stack traces / internal paths to the client.
app.use((err, req, res, next) => {
  console.error('Unhandled error:', err);
  res.status(err.status || 500).json({ error: 'internal_error' });
});

app.listen(PORT, () => {
  console.log(`cowhand rodando na porta ${PORT}`);
});
